[tool.poetry]
name = "app"
version = "0.1.0"
description = "LangChain playground boilerplate project."
authors = ["baxy5 <bakos.soda@gmail.com>"]

[tool.poetry.scripts]
start = 'app.server:main'

[tool.poetry.dependencies]
python = "^3.9"
fastapi = { extras = ["standard"], version = "^0.116.1" }
uvicorn = "^0.35.0"
langgraph = "^0.6.6"
langchain = { extras = ["openai"], version = "^0.3.27" }
black = "^25.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
